apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ekscluster-reservationapp
  labels: 
     app: reservationapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: reservationapp

  template:
    metadata:
      labels:
        app: reservationapp
    spec:
      containers:
      - name: reservationapp
        image: tanu2802/reservationapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1