apiVersion: v1
kind: Service
metadata:
  name: ekscluster-service
  labels:
    app: reservationapp 
spec:
  selector:
    app: reservationapp 

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer